# Generated by Django 5.0.7 on 2024-08-03 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='photo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='screening',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='screening',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
